= Code Submission for 8th Light
Benjamin b.james.neustadt@gmail.com
:copyright: © 2022 Benjamin
:doctype: article
:icons: font
:toc: left
:toclevels: 2
:toc-title: Table of Contents
:source-highlighter: rouge
:rouge-style: monokai
//URLS
:url-google-api-medium: https://rachelaemmer.medium.com/how-to-use-the-google-books-api-in-your-application-17a0ed7fa857


= Usage

1. Install Ruby
2. Install dependencies
3. Run the program: `ruby bin/bookview.rb`

== Set-Up Instructions

To use this application, clone this repo to your local with the following command:

`git clone https://github.com/BenjaminNeustadt/8th_light_test.git`

Ensure that you have Ruby downloaded on your system, you can check by inputting `ruby -v` into your terminal.

Run `bundle install` to ensure you have all the correct dependencies of this project.

== To use this program live

****
[NOTE]
====

If you would like to use this program online, the steps will be as follows:

1. Setup your own google Books API_KEY,{url-google-api-medium}[this article] is very helpful.
2. create a '.env' file in the root directory using the following layout:

[source, json]
----
#.env file
{ "API_KEY" : "[YOUR_API_KEY_HERE]" } <1>
----
<1> You will only need one set of quotation marks surrounding the key.

3. In the executable file ('bin/bookview.rb'), comment out line 64, and uncomment the corresponding line below(line 66).
In short, `BookSearch.new` should be given an argument of `BookData.new(query).parse`.
4. You can now use the program live.
====
****

== Using the Program

From within the root directory of the program,
in your terminal:

[source, sh]
----
ruby bin/bookview.rb
----

Follow the prompts to search for a book query.
Insert any word to get a return of 5 books that match your query.
Follow the prompts to add the book to a reading list.


[IMPORTANT]
(Please note, the queries will only be matched via the Google Books API
if you set the program to online, else it will use persistent test data.)

= Testing

The testing framework used is Rspec.
Code coverage is around 96%.

.To run the tests:
[source, sh]
----
rspec -fd
----

= Process

Following is some of the initial planning,
followed by some revisoinary CRC modelling post review.

== CRC Model Planning

=== Initially the following design was considered.

_Class Responsibility Collaborator_

_Following a Model/View/Controller design_

         Front-end                                 Back-end
 - - - - - - - - - - - - - -    - - - - - - - - - - - - - - - - - - - - - - - - - - -

   Public facing interface          Operation                 Storage
   (Command line interface)
  ┌───────────────────────┐     ┌───────────────────────┐    ┌───────────────────────┐
  │  BookSearch           │     │  BookList             │    │  UserList             │
  │              BookList │     │            BookSearch │    │        BookSearch,BookList
  ├──────────────┬────────┤     ├──────────────┬────────┤    ├──────────────┬─────────
  │.Give         │        │     │.grab_books   │        │    │.Store users  │.BookList
  │ instructions │.BookList     │              │        │    │ chosen books │        │
  │ to user      │        │     │.search       │        │    │              │.BookSearch
  │.Pass         │        │     │              │        │    │.Pass array   │        │
  │ instructions │        │     │.add (instantiates     │    │ of books to  │        │
  │ to BookList  │        │     │instance of UserList   │    │ BookSearch   │        │
  │.Retrive Userlist      │     │              │        │    │              │        │
  │ (stored book data)    │     │              │        │    │              │        │
  │              │        │     │              │        │    │              │        │
  └──────────────┴────────┘     └──────────────┴────────┘    └──────────────┴────────┘

            VIEW                         CONTROLLER                     MODEL


=== Post review

[NOTE]
Not all of these constants have been implemented (specifically the 3 modules);
and BookView has not been refactored accordingly.
However, this is a design that feels like it would adher more correctly to the Single Responsibility Principle,
and other SOLID priniciples.


          ┌───────┬───────────┐   ┌────────┬───────┐    ┌────────┬───────┐
          │ module│decorators │   │ module │Prompt │    │ module │Report │
          ├───────┴───────────┤   ├────────┴───────┤    ├────────┴───────┤
          │                   │   │                │    │                │
          │ .Holds border     │   │ .Holds MENU    │    │ .Holds all     │
          │  decorators/      │   │  constant      │    │  report methods│
          │  styling          │   │                │    │                │
          │                   │   │ .menu method   │    │ .Holds REPORT  │
          │                   │   │  for presenting│    │  constant      │
          │                   │   │  to user       │    │  for string    │
          │                   │   │                │    │  layouts       │
          │                   │   │                │    │                │
          │                   │   │                │    │                │
          └───────────────────┘   └────────────────┘    └────────────────┘

                    Modules for conataing constants and methods
         ---------------------------------------------------------------------



          PUBLIC FACING INTERFACE
       ┌─┬────────────────────────┬─┐
       │ ├────────────────────────┤ │             ┌───────────────────────┐     ┌───────────────────────┐
       │ │  BookView              │ │             │  BookSearch           │     │  BookStorage          │
       │ │                        │ │             │                       │     │            BookSearch │
       │ ├───────────────┬────────┘ │             ├────────────┬──────────┘     ├──────────────┬────────┤
       │ │               │BookStorage             │ .After     │ BookStorage    │.Store users  │        │
       │ │ .look_up_books│BookSearch│             │  receiving │ TestData │     │ chosen books │        │
       │ │               │        │ │             │  data      │ BookData │     │              │        │
       │ │ .add_book     │        │ │             │  extract   │          │     │ .Can add     │        │
       │ │               │        │ │             │  attributes│          │     │  book        │        │
       │ │ .includes 3   │        │ │             │            │          │     │              │        │
       │ │  modules:     │        │ │             │            │          │     │              │        │
       │ │  Report       │        │ │             │            │          │     │              │        │
       │ │  Prompt       │        │ │             │            │          │     │              │        │
       │ │               │        │ │             └────────────┴──────────┘     └──────────────┴────────┘
       │ ├───────────────┼────────┤ │
       └─┴────────────────────────┴─┘                         ▲      ▲
                                                              │      │
                    │                                ┌────────┘      └──────────┐
                    │                                │                          │
                    │                                │                          │
                    ▼                                │                          │
          |---------------------|         ┌──────────┴────────────┐   ┌─────────┴─────────────┐
          |.Give                |         │ TestData              │   │ BookData              │
          | instructions        |         │            BookSearch │   │            BookSearch │
          | to user             |         ├──────────────┬────────┤   ├──────────────┬────────┤
          |.Pass                |         │.Connection   │        │   │.HTTP request │        │
          | instructions        |         │ to test_data │        │   │ to the       │        │
          | to BookSearch       |         │ upon         │        │   │ API with     │        │
          |.Retrieve books      |         │ initialize   │        │   │ parse method │        │
          | (from BookStorage)  |         │              │        │   │              │        │
          |---------------------|         │              │        │   │.Holds:       │        │
                                          │              │        │   │ URL          │        │
                                          │              │        │   │ constant     │        │
                                          │              │        │   │ API_key connector     │
                                          └──────────────┴────────┘   └───────────────────────┘

                                           (Passed as argument            (Passed as argument
                                           when in a dev environment)     when going live)



= Initial Brief

Create a command line application that allows you to use the
Google Books AP search for books and construct a reading list.

You do not have to use a private GitHub repo for this.

_This application should allow you to:_

1. Type in a query and display a list of *5 books matching that query.*
2. Each item in the list should include the book's author, title, and publishing
  company.
3. A user should be able to select a book from the five displayed to save to a
  “Reading List” View a “Reading List” with all the books the user has selected
  from their queries
  - this is a local reading list and not tied to Google
  Books’s account features.
4. For programming language, choose any language you want as long as it is not
  the same language you chose to review in the Code Review section above.
5. Feel free to use a library (or not) for the Google Books call or JSON parsing.

Please do not add any additional features.

Your submission doesn’t need to be perfect.

After we receive your submission we'll review your code, respond to you with
our feedback and suggestions, and give you an opportunity to respond to our
feedback and make improvements to your code before you re-submit a second and
final version.

That said, we would still like to see your best work with the first version you submit.
It should demonstrate external quality (for example: solves the problem,
handles edge cases, usability), internal quality (for example:
*decoupling*, *testing*, *readability*), as well as some idea of your process and
approach (via your version control history and README).

= Post review stretch goals

_Question_
With the Single Responsibility Principle in mind, what are all of the
responsibilities of the bin/bookview.rb script in its current form? Given the
time, how might you refactor so that the script has a single responsibility?


Currently the responsibilities of bin/bookview.rb are numerous:
* running the script/loop
* holding two constants for later use within this file
* instantiating an instance of the 'BookStorage' class
* contains methods used within this method

Initially when writing this I followed a sort of procedural programming style of writing the code.
However, I would definitely like to improve this.

In light of SRP I would ideally do the following, in approximately this order:
* create a 'class BookView'
** in its initialize method I would like to instantiate an instance of 'BookStorage'
** It could hold two main methods:
*** 'look_up_books(query)'
*** 'add_book' which would store it inside the instance of 'BookStorage'
** I would like to refactor much of the code inside the actual loop, as I feel that the script should only really instantiate a public interface object once (i.e. `session = BookView.new`)
*** I would first consider extracting a 'menu' method from the loop (lines 45-47)
*** I would at first leave this inside the 'BookView class'

Within each when case of the loop, there is business logic for reporting the
instances of `@search_results` and `@users_storage`, and I feel this would be
great opportunity to extract these into report methods
I can envision a :
`report_search_results`
`report_search_results`

