= Code Submission for 8th Light

== Instructions

Create a command line application that allows you to use the
Google Books API to search for books and construct a reading list.

You do not have to use a private GitHub repo for this.

_This application should allow you to:_

1. Type in a query and display a list of 5 books matching that query.
2. Each item in the list should include the book's author, title, and publishing
  company.
3. A user should be able to select a book from the five displayed to save to a
  “Reading List” View a “Reading List” with all the books the user has selected
  from their queries 
  - this is a local reading list and not tied to Google
  Books’s account features.
4. For programming language, choose any language you want as long as it is not
  the same language you chose to review in the Code Review section above.
5. Feel free to use a library (or not) for the Google Books call or JSON parsing.

Please do not add any additional features.

Your submission doesn’t need to be perfect.

After we receive your submission we'll review your code, respond to you with
our feedback and suggestions, and give you an opportunity to respond to our
feedback and make improvements to your code before you re-submit a second and
final version.

That said, we would still like to see your best work with the first version you submit.
It should demonstrate external quality (for example: solves the problem,
handles edge cases, usability), internal quality (for example:
*decoupling*, *testing*, *readability*), as well as some idea of your process and
approach (via your version control history and README).


To use this application, clone this repo to your local with the following command:

`git clone [repo]`

the API key used in this project is restricted (mine) so head [here](https://developers.google.com/books/docs/v1/using#APIKey) and follow the instructions to get your own.

Currently the API key I am going to use is: 'AIzaSyDTsdQz7h-sK8Kf3shcnXrsLT1rWj5PYak'

Ensure that you have Ruby downloaded on your system, you can check by inputting `ruby -v` into your terminal.

run `bundle install` to ensure you have all the correct dependencies of this project.

I use this article to set up the google api key correctly:

https://rachelaemmer.medium.com/how-to-use-the-google-books-api-in-your-application-17a0ed7fa857

I went here: https://console.cloud.google.com/apis/api/books.googleapis.com/credentials?project=my-test-project-371917

to enable 'Books API', when we type the following into the console we get the return of raw json data:

https://www.googleapis.com/books/v1/volumes?q=history&key=AIzaSyDTsdQz7h-sK8Kf3shcnXrsLT1rWj5PYak

= Testing

First step will be checking if we can get a valid response:

Something like:

```rb
#rspec test for connection

describe "API call" do
  it "has a valid HTTP connection" do
    api_url="api url"
    response = Net::HTTP.get_response(URI(api_url))
    expect(response.is_a?(Net::HTTPSuccess)).to be true
  end
end
```

To get test data to use repeatedly in our tests, we used the following command:

`curl "https://www.googleapis.com/books/v1/volumes?q=history&key=[API_KEY]" -o test_data1.json`

we can then `bat` the file to see the file properly formatted.
